pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
				dir('s3-azure-connector') {
					sh 'chmod +x mvnw'
                	sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                dir('s3-azure-connector') {
                    sshagent(credentials: ['ec2-ssh-key']) {
                        sh '''
                            scp -o StrictHostKeyChecking=no \
                            target/s3-azure-connector-0.0.1-SNAPSHOT.jar \
                            ubuntu@${EC2_HOST}:/home/ubuntu/s3-azure-connector.jar

                            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} \
                            'nohup env \
                            AWS_REGION=us-east-1 \
                            S3_BUCKET_NAME=jacob-10232025 \
                            AZURE_BLOB_CONTAINER_NAME=s3files \
                            AZURE_CONNECTION_SECRET_NAME=azure-storage-connection-string \
                            java -jar /home/ubuntu/s3-azure-connector.jar \
                            > /home/ubuntu/s3-azure-connector.log 2>&1 < /dev/null &'
                        '''
                    }
                }
            }
        }
    }
}