spring.application.name=s3-azure-connector

aws.region=${AWS_REGION}
aws.s3.bucket.name=${S3_BUCKET_NAME}
azure.blob.container.name=${AZURE.BLOB.CONTAINER.NAME}
azure.blob.connection-string= ${AZURE_STORAGE_CONNECTION_STRING}