spring.application.name=s3-azure-connector

aws.region=${AWS_REGION}
aws.s3.bucket-name=${S3_BUCKET_NAME}
azure.blob.container-name=${AZURE_BLOB_CONTAINER_NAME}
azure.blob.secret-name= ${AZURE_CONNECTION_SECRET_NAME}

azure.eventhub.secret-name=${AZURE_EVENTHUB_SECRET_NAME}
azure.eventhub.event-hub-name=${AZURE_EVENTHUB_NAME}